#Requires -Version 5.1
<#
.SYNOPSIS
    Watches for controller connections and switches display profile,
    audio device, FRL cap, and launches Playnite automatically.
    Edit config.psd1 to change mappings. Do not edit this file.
#>

Set-StrictMode -Off
$ErrorActionPreference = "Continue"

# ============================================================
# Logging
# ============================================================
$global:LogFile = "$PSScriptRoot\controller_watch.log"

# Rotate log if it grows past ~1 MB.  Keeps one previous generation.
try {
    if (Test-Path -LiteralPath $global:LogFile) {
        $sz = (Get-Item -LiteralPath $global:LogFile).Length
        if ($sz -gt 1MB) {
            $old = "$global:LogFile.old"
            if (Test-Path -LiteralPath $old) { Remove-Item -LiteralPath $old -Force -ErrorAction SilentlyContinue }
            Move-Item -LiteralPath $global:LogFile -Destination $old -Force -ErrorAction SilentlyContinue
        }
    }
} catch {}

function Write-Log {
    param([string]$Msg)
    $line = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff')  $Msg"
    Add-Content -Path $global:LogFile -Value $line -Encoding UTF8
    Write-Host $line
}

# ============================================================
# Load config
# ============================================================
function Convert-LegacyConfigPs1ToData {
    param([Parameter(Mandatory=$true)][string]$Path)

    $tokens = $null
    $errors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errors)
    if ($errors -and $errors.Count -gt 0) {
        throw "Legacy config parse failed: $($errors[0].Message)"
    }

    $allowed = @{
        cfg_FRLToggle = 'FRLToggle'
        cfg_NirCmd = 'NirCmd'
        cfg_Playnite = 'Playnite'
        cfg_HueSync = 'HueSync'
        cfg_CustomApp = 'CustomApp'
        cfg_CustomAppLabel = 'CustomAppLabel'
        cfg_CustomApps = 'CustomApps'
        cfg_Profiles = 'Profiles'
        cfg_DesktopProfile = 'DesktopProfile'
        cfg_ControllerMap = 'ControllerMap'
        cfg_ControllerContainerMap = 'ControllerContainerMap'
        cfg_DebounceSeconds = 'DebounceSeconds'
        cfg_FocusTarget = 'FocusTarget'
        cfg_AudioDelayMs = 'AudioDelayMs'
        cfg_PollMs = 'PollMs'
    }

    $data = @{}
    $statements = @()
    if ($ast.EndBlock) { $statements = @($ast.EndBlock.Statements) }
    foreach ($stmt in $statements) {
        if ($stmt -isnot [System.Management.Automation.Language.AssignmentStatementAst]) {
            throw "Legacy config contains executable statement '$($stmt.Extent.Text.Trim())'. Re-run the setup wizard to create config.psd1."
        }
        if ($stmt.Left -isnot [System.Management.Automation.Language.VariableExpressionAst]) {
            throw "Legacy config contains an unsupported assignment. Re-run the setup wizard to create config.psd1."
        }

        $varName = $stmt.Left.VariablePath.UserPath
        if (-not $allowed.ContainsKey($varName)) {
            throw "Legacy config contains unsupported variable '$varName'. Re-run the setup wizard to create config.psd1."
        }
        if (-not ($stmt.Right -is [System.Management.Automation.Language.CommandExpressionAst]) -or -not $stmt.Right.Expression) {
            throw "Legacy config assignment '$varName' is not a literal value."
        }

        try {
            $data[$allowed[$varName]] = $stmt.Right.Expression.SafeGetValue()
        } catch {
            throw "Legacy config assignment '$varName' is not a safe literal value: $($_.Exception.Message)"
        }
    }
    return $data
}

function Import-SofaShiftConfigData {
    param([Parameter(Mandatory=$true)][string]$BaseDir)

    $dataPath = Join-Path $BaseDir "config.psd1"
    $legacyPath = Join-Path $BaseDir "config.ps1"

    if (Test-Path -LiteralPath $dataPath) {
        Write-Log "Loading config.psd1"
        return (Import-PowerShellDataFile -LiteralPath $dataPath)
    }

    if (Test-Path -LiteralPath $legacyPath) {
        Write-Log "Loading legacy config.ps1 as data only; executable statements are refused"
        return (Convert-LegacyConfigPs1ToData -Path $legacyPath)
    }

    throw "No config found. Expected config.psd1 at $dataPath"
}

function Set-SofaShiftConfigVariables {
    param([Parameter(Mandatory=$true)][hashtable]$Data)

    $global:cfg_FRLToggle = if ($Data.ContainsKey('FRLToggle')) { [string]$Data.FRLToggle } else { '' }
    $global:cfg_NirCmd = if ($Data.ContainsKey('NirCmd')) { [string]$Data.NirCmd } else { '' }
    $global:cfg_Playnite = if ($Data.ContainsKey('Playnite')) { [string]$Data.Playnite } else { '' }
    $global:cfg_HueSync = if ($Data.ContainsKey('HueSync')) { [string]$Data.HueSync } else { '' }
    $global:cfg_CustomApp = if ($Data.ContainsKey('CustomApp')) { [string]$Data.CustomApp } else { '' }
    $global:cfg_CustomAppLabel = if ($Data.ContainsKey('CustomAppLabel')) { [string]$Data.CustomAppLabel } else { '' }
    $global:cfg_CustomApps = if ($Data.ContainsKey('CustomApps') -and $Data.CustomApps) { @($Data.CustomApps) } else { @() }
    $global:cfg_Profiles = if ($Data.ContainsKey('Profiles') -and $Data.Profiles) { $Data.Profiles } else { @{} }
    $global:cfg_DesktopProfile = if ($Data.ContainsKey('DesktopProfile')) { [string]$Data.DesktopProfile } else { '' }
    $global:cfg_ControllerMap = if ($Data.ContainsKey('ControllerMap') -and $Data.ControllerMap) { $Data.ControllerMap } else { @{} }
    $global:cfg_ControllerContainerMap = if ($Data.ContainsKey('ControllerContainerMap') -and $Data.ControllerContainerMap) { $Data.ControllerContainerMap } else { @{} }
    $global:cfg_DebounceSeconds = if ($Data.ContainsKey('DebounceSeconds')) { [int]$Data.DebounceSeconds } else { 10 }
    $global:cfg_FocusTarget = if ($Data.ContainsKey('FocusTarget') -and $Data.FocusTarget) { [string]$Data.FocusTarget } else { 'Playnite' }
    $global:cfg_AudioDelayMs = if ($Data.ContainsKey('AudioDelayMs')) { [int]$Data.AudioDelayMs } else { 3000 }
    if ($Data.ContainsKey('PollMs')) { $global:cfg_PollMs = [int]$Data.PollMs }
}

try {
    $configData = Import-SofaShiftConfigData -BaseDir $PSScriptRoot
    Set-SofaShiftConfigVariables -Data $configData
} catch {
    Write-Log "Failed to load SofaShift config: $($_.Exception.Message)"
    exit 1
}

if (-not $cfg_ControllerMap -or $cfg_ControllerMap.Keys.Count -eq 0) {
    Write-Log "No controllers are mapped in config.psd1. Exiting."
    exit 1
}

# ============================================================
# Config cross-reference validation
# Log (but don't exit) when the config references profiles/files that don't exist.
# This makes debugging a broken setup much faster - the user sees the exact problem
# in the log instead of a silent failure to switch displays.
# ============================================================
$cfgIssues = [System.Collections.Generic.List[string]]::new()

if (-not $cfg_Profiles -or $cfg_Profiles.Keys.Count -eq 0) {
    $cfgIssues.Add("cfg_Profiles is empty - no display profiles defined")
}

if ($cfg_Profiles -and $cfg_DesktopProfile -and -not $cfg_Profiles.ContainsKey($cfg_DesktopProfile)) {
    $cfgIssues.Add("cfg_DesktopProfile '$cfg_DesktopProfile' is not a defined profile in cfg_Profiles")
}

if ($cfg_Profiles -and $cfg_ControllerMap) {
    foreach ($devId in $cfg_ControllerMap.Keys) {
        $target = $cfg_ControllerMap[$devId]
        if ($target -and -not $cfg_Profiles.ContainsKey($target)) {
            $cfgIssues.Add("Controller '$devId' maps to profile '$target' which is not defined in cfg_Profiles")
        }
    }
}

if ($cfg_Profiles) {
    foreach ($name in $cfg_Profiles.Keys) {
        $p = $cfg_Profiles[$name]
        if (-not ($p.TargetId -and [uint32]$p.TargetId -gt 0)) {
            $cfgIssues.Add("Profile '$name' has no native CCD target configured (TargetId is 0).")
        }
    }
}

# Tool paths referenced in config
if ($cfg_NirCmd -and -not (Test-Path -LiteralPath $cfg_NirCmd)) {
    $cfgIssues.Add("cfg_NirCmd not found on disk: $cfg_NirCmd")
}
if ($cfg_Playnite -and -not (Test-Path -LiteralPath $cfg_Playnite)) {
    $cfgIssues.Add("cfg_Playnite not found on disk: $cfg_Playnite")
}

if ($cfgIssues.Count -gt 0) {
    Write-Log "Config validation: $($cfgIssues.Count) issue(s) detected:"
    foreach ($issue in $cfgIssues) { Write-Log "  - $issue" }
    Write-Log "Continuing with partial config - re-run the setup wizard to fix."
} else {
    Write-Log "Config validation: OK"
}

# ============================================================
# Single-instance guard (named mutex, per-user)
# Previous version parsed Win32_Process command-lines, which is slow, needs CIM permission,
# and can misfire across renames. A session-scoped mutex is cleaner and self-cleans on exit.
# ============================================================
$global:SingleInstanceMutex = $null
try {
    $created = $false
    $mutexName = "Local\SofaShift.ControllerWatch.$($env:USERNAME)"
    $global:SingleInstanceMutex = New-Object System.Threading.Mutex($true, $mutexName, [ref]$created)
    if (-not $created) {
        Write-Log "Another SofaShift watcher is already running for this user - exiting."
        exit 0
    }
} catch {
    Write-Log "Single-instance mutex check failed ($($_.Exception.Message)) - continuing anyway."
}

Write-Log ("=" * 56)
Write-Log "Starting controller monitor"
Write-Log "Watching controllers:"
foreach ($id in $cfg_ControllerMap.Keys) {
    Write-Log "  $id  =>  $($cfg_ControllerMap[$id])"
}

# Poll interval - respect cfg_PollMs if defined in config, else default to 1000 ms.
# Clamp to a sane range so a typo in config can't melt the CPU.
$script:PollMs = 1000
if (Get-Variable -Name 'cfg_PollMs' -Scope Global -ErrorAction SilentlyContinue) {
    $candidate = 0
    if ([int]::TryParse([string]$cfg_PollMs, [ref]$candidate) -and $candidate -ge 100 -and $candidate -le 10000) {
        $script:PollMs = $candidate
    }
}
Write-Log "DebounceSeconds=$cfg_DebounceSeconds  PollMs=$script:PollMs"
Write-Log "Press Ctrl+C to stop."
Write-Log ("=" * 56)

# ============================================================
# Win32 helper for SetForegroundWindow
# ============================================================
Add-Type -Namespace XCS -Name User32 -MemberDefinition @"
[System.Runtime.InteropServices.DllImport("user32.dll")]
public static extern bool SetForegroundWindow(System.IntPtr hWnd);

private delegate bool EnumWindowsProc(System.IntPtr hWnd, System.IntPtr lParam);

[System.Runtime.InteropServices.DllImport("user32.dll")]
private static extern bool EnumWindows(EnumWindowsProc lpEnumFunc, System.IntPtr lParam);

[System.Runtime.InteropServices.DllImport("user32.dll")]
private static extern bool IsWindowVisible(System.IntPtr hWnd);

[System.Runtime.InteropServices.DllImport("user32.dll", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
private static extern int GetWindowText(System.IntPtr hWnd, System.Text.StringBuilder lpString, int nMaxCount);

[System.Runtime.InteropServices.DllImport("user32.dll", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
private static extern int GetWindowTextLength(System.IntPtr hWnd);

public static System.IntPtr FindWindowByTitleRegex(string pattern)
{
    if (string.IsNullOrWhiteSpace(pattern)) return System.IntPtr.Zero;

    System.Text.RegularExpressions.Regex re;
    try {
        re = new System.Text.RegularExpressions.Regex(pattern, System.Text.RegularExpressions.RegexOptions.IgnoreCase);
    } catch {
        return System.IntPtr.Zero;
    }

    System.IntPtr found = System.IntPtr.Zero;
    EnumWindows(delegate(System.IntPtr hWnd, System.IntPtr lParam) {
        if (!IsWindowVisible(hWnd)) return true;
        int len = GetWindowTextLength(hWnd);
        if (len <= 0) return true;
        var sb = new System.Text.StringBuilder(len + 1);
        if (GetWindowText(hWnd, sb, sb.Capacity) <= 0) return true;
        if (re.IsMatch(sb.ToString())) {
            found = hWnd;
            return false;
        }
        return true;
    }, System.IntPtr.Zero);
    return found;
}
"@ -ErrorAction SilentlyContinue

# ============================================================
# Normalize watched controller IDs once at startup.
# Polling filters in PowerShell instead of building a WMI query,
# which avoids "Invalid query" failures from escaped device paths.
# ============================================================
$global:WatchedControllerIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$global:WatchedContainerIds  = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
# Canonical ID -> profile name.  Keys are either HID instance paths (from cfg_ControllerMap)
# or Container GUIDs (from cfg_ControllerContainerMap).  Container IDs are used when the
# Xbox wireless adapter assigns a different instance path to the same physical controller
# depending on how many controllers are connected (slot assignment is volatile).
$global:CanonicalIdToProfile = @{}

foreach ($id in $cfg_ControllerMap.Keys) {
    if (-not [string]::IsNullOrWhiteSpace([string]$id)) {
        $trimmed = ([string]$id).Trim()
        [void]$global:WatchedControllerIds.Add($trimmed)
        $global:CanonicalIdToProfile[$trimmed] = $cfg_ControllerMap[$id]
    }
}

# Load container ID map if the config has one (generated by wizard >= this version).
if (Get-Variable cfg_ControllerContainerMap -Scope Global -ErrorAction SilentlyContinue) {
    foreach ($cid in $cfg_ControllerContainerMap.Keys) {
        if (-not [string]::IsNullOrWhiteSpace([string]$cid)) {
            $trimmed = ([string]$cid).Trim()
            [void]$global:WatchedContainerIds.Add($trimmed)
            $global:CanonicalIdToProfile[$trimmed] = $cfg_ControllerContainerMap[$cid]
        }
    }
}

Write-Log "Watching $($global:WatchedControllerIds.Count) mapped controller ID(s)$(if ($global:WatchedContainerIds.Count -gt 0) { " + $($global:WatchedContainerIds.Count) container ID(s) for slot-stable matching" })"


# ============================================================
# Modern Windows CCD helper (native display switching)
# ============================================================
Add-Type -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

public class SofaCcd
{
    public const uint QDC_ALL_PATHS = 0x00000001;
    public const uint QDC_VIRTUAL_MODE_AWARE = 0x00000010;
    public const int DISPLAYCONFIG_PATH_ACTIVE = 0x00000001;
    public const uint DISPLAYCONFIG_PATH_MODE_IDX_INVALID = 0xFFFFFFFF;
    public const uint SDC_TOPOLOGY_SUPPLIED = 0x00000010;
    public const uint SDC_USE_SUPPLIED_DISPLAY_CONFIG = 0x00000020;
    public const uint SDC_APPLY = 0x00000080;
    public const uint SDC_SAVE_TO_DATABASE = 0x00000200;
    public const uint SDC_ALLOW_CHANGES = 0x00000400;
    public const uint SDC_PATH_PERSIST_IF_REQUIRED = 0x00000800;
    public const uint SDC_VIRTUAL_MODE_AWARE = 0x00008000;
    public const uint SDC_VIRTUAL_REFRESH_RATE_AWARE = 0x00020000;
    public const uint DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1;
    public const uint DISPLAYCONFIG_PIXELFORMAT_32BPP = 4;
    public const uint DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1;
    public const uint DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2;

    // ChangeDisplaySettingsEx constants
    public const int ENUM_CURRENT_SETTINGS = -1;
    public const int DM_PELSWIDTH        = 0x00080000;
    public const int DM_PELSHEIGHT       = 0x00100000;
    public const int DM_DISPLAYFREQUENCY = 0x00400000;
    public const int CDS_UPDATEREGISTRY  = 0x00000001;

    [StructLayout(LayoutKind.Sequential)] public struct LUID { public uint LowPart; public int HighPart; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_RATIONAL { public uint Numerator; public uint Denominator; }
    [StructLayout(LayoutKind.Sequential)] public struct POINTL { public int x; public int y; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_PATH_SOURCE_INFO { public LUID adapterId; public uint id; public uint modeInfoIdx; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_PATH_TARGET_INFO { public LUID adapterId; public uint id; public uint modeInfoIdx; public uint outputTechnology; public uint rotation; public uint scaling; public DISPLAYCONFIG_RATIONAL refreshRate; public uint scanLineOrdering; public bool targetAvailable; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_PATH_INFO { public DISPLAYCONFIG_PATH_SOURCE_INFO sourceInfo; public DISPLAYCONFIG_PATH_TARGET_INFO targetInfo; public uint flags; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_SOURCE_MODE { public uint width; public uint height; public uint pixelFormat; public POINTL position; }
    [StructLayout(LayoutKind.Explicit)] public struct DISPLAYCONFIG_MODE_INFO_UNION { [FieldOffset(0)] public DISPLAYCONFIG_SOURCE_MODE sourceMode; }
    [StructLayout(LayoutKind.Sequential)] public struct DISPLAYCONFIG_MODE_INFO { public uint infoType; public uint id; public LUID adapterId; public DISPLAYCONFIG_MODE_INFO_UNION modeInfo; }

    [StructLayout(LayoutKind.Sequential)]
    public struct DISPLAYCONFIG_DEVICE_INFO_HEADER { public uint type; public uint size; public LUID adapterId; public uint id; }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DISPLAYCONFIG_SOURCE_DEVICE_NAME {
        public DISPLAYCONFIG_DEVICE_INFO_HEADER header;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
        public string viewGdiDeviceName;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS { public uint value; }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DISPLAYCONFIG_TARGET_DEVICE_NAME {
        public DISPLAYCONFIG_DEVICE_INFO_HEADER header;
        public DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS flags;
        public uint outputTechnology;
        public ushort edidManufactureId;
        public ushort edidProductCodeId;
        public uint connectorInstance;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
        public string monitorFriendlyDeviceName;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
        public string monitorDevicePath;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    public struct DEVMODE {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string dmDeviceName;
        public short dmSpecVersion, dmDriverVersion, dmSize, dmDriverExtra;
        public int dmFields, dmPositionX, dmPositionY, dmDisplayOrientation, dmDisplayFixedOutput;
        public short dmColor, dmDuplex, dmYResolution, dmTTOption, dmCollate;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string dmFormName;
        public short dmLogPixels;
        public int dmBitsPerPel, dmPelsWidth, dmPelsHeight, dmDisplayFlags, dmDisplayFrequency;
        public int dmICMMethod, dmICMIntent, dmMediaType, dmDitherType, dmReserved1, dmReserved2, dmPanningWidth, dmPanningHeight;
    }

    [DllImport("user32.dll")] public static extern int GetDisplayConfigBufferSizes(uint flags, out uint numPathArrayElements, out uint numModeInfoArrayElements);
    [DllImport("user32.dll")] public static extern int QueryDisplayConfig(uint flags, ref uint numPathArrayElements, [Out] DISPLAYCONFIG_PATH_INFO[] pathArray, ref uint numModeInfoArrayElements, [Out] DISPLAYCONFIG_MODE_INFO[] modeInfoArray, IntPtr currentTopologyId);
    [DllImport("user32.dll")] public static extern int SetDisplayConfig(uint numPathArrayElements, [In] DISPLAYCONFIG_PATH_INFO[] pathArray, uint numModeInfoArrayElements, [In] DISPLAYCONFIG_MODE_INFO[] modeInfoArray, uint flags);
    [DllImport("user32.dll", EntryPoint = "DisplayConfigGetDeviceInfo")]
    public static extern int DisplayConfigGetDeviceInfoSource(ref DISPLAYCONFIG_SOURCE_DEVICE_NAME requestPacket);
    [DllImport("user32.dll", EntryPoint = "DisplayConfigGetDeviceInfo")]
    public static extern int DisplayConfigGetDeviceInfoTarget(ref DISPLAYCONFIG_TARGET_DEVICE_NAME requestPacket);
    [DllImport("user32.dll", CharSet = CharSet.Ansi)]
    public static extern bool EnumDisplaySettings(string deviceName, int modeNum, ref DEVMODE devMode);
    [DllImport("user32.dll", CharSet = CharSet.Ansi)]
    public static extern int ChangeDisplaySettingsEx(string lpszDeviceName, ref DEVMODE lpDevMode, IntPtr hwnd, int dwFlags, IntPtr lParam);

    static void Query(out DISPLAYCONFIG_PATH_INFO[] paths, out DISPLAYCONFIG_MODE_INFO[] modes)
    {
        uint pathCount, modeCount;
        int rc;
        do {
            rc = GetDisplayConfigBufferSizes(QDC_ALL_PATHS, out pathCount, out modeCount);
            if (rc != 0) throw new InvalidOperationException("GetDisplayConfigBufferSizes failed: " + rc);
            paths = new DISPLAYCONFIG_PATH_INFO[pathCount];
            modes = new DISPLAYCONFIG_MODE_INFO[modeCount];
            rc = QueryDisplayConfig(QDC_ALL_PATHS, ref pathCount, paths, ref modeCount, modes, IntPtr.Zero);
            if (rc == 122) continue;
            if (rc != 0) throw new InvalidOperationException("QueryDisplayConfig failed: " + rc);
            if (pathCount != paths.Length) Array.Resize(ref paths, (int)pathCount);
            if (modeCount != modes.Length) Array.Resize(ref modes, (int)modeCount);
            break;
        } while (true);
    }

    public class TargetRecord {
        public uint AdapterLow { get; set; }
        public int AdapterHigh { get; set; }
        public uint SourceId { get; set; }
        public uint TargetId { get; set; }
        public string DevicePath { get; set; }
        public string Friendly { get; set; }
        public bool IsActive { get; set; }
        public bool TargetAvailable { get; set; }
    }

    static string TargetName(LUID adapterId, uint targetId, out string devicePath)
    {
        devicePath = "";
        var target = new DISPLAYCONFIG_TARGET_DEVICE_NAME();
        target.header.size = (uint)Marshal.SizeOf(typeof(DISPLAYCONFIG_TARGET_DEVICE_NAME));
        target.header.adapterId = adapterId;
        target.header.id = targetId;
        target.header.type = DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME;
        int rc = DisplayConfigGetDeviceInfoTarget(ref target);
        if (rc != 0) return "";
        devicePath = target.monitorDevicePath ?? "";
        return string.IsNullOrWhiteSpace(target.monitorFriendlyDeviceName) ? "" : target.monitorFriendlyDeviceName.Trim();
    }

    static bool SameText(string left, string right)
    {
        return !string.IsNullOrWhiteSpace(left) &&
               !string.IsNullOrWhiteSpace(right) &&
               string.Equals(left.Trim(), right.Trim(), StringComparison.OrdinalIgnoreCase);
    }

    static TargetRecord ToTargetRecord(DISPLAYCONFIG_PATH_INFO path, string devicePath, string friendly)
    {
        return new TargetRecord {
            AdapterLow = path.targetInfo.adapterId.LowPart,
            AdapterHigh = path.targetInfo.adapterId.HighPart,
            SourceId = path.sourceInfo.id,
            TargetId = path.targetInfo.id,
            DevicePath = devicePath ?? "",
            Friendly = friendly ?? "",
            IsActive = (path.flags & DISPLAYCONFIG_PATH_ACTIVE) != 0,
            TargetAvailable = path.targetInfo.targetAvailable
        };
    }

    public static TargetRecord ResolveTarget(uint adapterLow, int adapterHigh, uint sourceId, uint targetId, string savedDevicePath, string savedFriendly)
    {
        DISPLAYCONFIG_PATH_INFO[] paths;
        DISPLAYCONFIG_MODE_INFO[] modes;
        Query(out paths, out modes);

        bool hasSavedDevicePath = !string.IsNullOrWhiteSpace(savedDevicePath);
        TargetRecord bestStable = null;
        int bestStableScore = Int32.MinValue;
        var friendlyMatches = new List<TargetRecord>();

        foreach (var p in paths) {
            string devicePath;
            string friendly = TargetName(p.targetInfo.adapterId, p.targetInfo.id, out devicePath);
            bool exactTarget = (p.targetInfo.adapterId.LowPart == adapterLow &&
                                p.targetInfo.adapterId.HighPart == adapterHigh &&
                                p.targetInfo.id == targetId);
            bool pathMatch = SameText(savedDevicePath, devicePath);
            bool friendlyMatch = SameText(savedFriendly, friendly);

            if (hasSavedDevicePath) {
                if (!pathMatch) continue;
            } else if (!exactTarget && !friendlyMatch) {
                continue;
            }

            var record = ToTargetRecord(p, devicePath, friendly);
            if (pathMatch || (!hasSavedDevicePath && exactTarget)) {
                int score = 0;
                if (pathMatch) score += 10000;
                if (exactTarget) score += 1000;
                if (record.TargetAvailable) score += 500;
                if (record.IsActive) score += 250;
                if (p.sourceInfo.id == sourceId) score += 25;
                if (score > bestStableScore) {
                    bestStableScore = score;
                    bestStable = record;
                }
            } else if (!hasSavedDevicePath && friendlyMatch) {
                friendlyMatches.Add(record);
            }
        }

        if (hasSavedDevicePath) return bestStable;

        TargetRecord friendlyFallback = null;
        if (friendlyMatches.Count == 1) friendlyFallback = friendlyMatches[0];

        TargetRecord onlyAvailableFriendly = null;
        bool ambiguousAvailableFriendly = false;
        foreach (var record in friendlyMatches) {
            if (!record.TargetAvailable && !record.IsActive) continue;
            if (onlyAvailableFriendly != null) {
                ambiguousAvailableFriendly = true;
                onlyAvailableFriendly = null;
                break;
            }
            onlyAvailableFriendly = record;
        }
        if (!ambiguousAvailableFriendly && onlyAvailableFriendly != null) friendlyFallback = onlyAvailableFriendly;

        if (bestStable != null) {
            if (bestStable.TargetAvailable || bestStable.IsActive || friendlyFallback == null)
                return bestStable;
            if (friendlyFallback.TargetAvailable || friendlyFallback.IsActive)
                return friendlyFallback;
            return bestStable;
        }

        return friendlyFallback;
    }

    public static bool GetTargetAvailable(uint adapterLow, int adapterHigh, uint targetId)
    {
        try {
            DISPLAYCONFIG_PATH_INFO[] paths;
            DISPLAYCONFIG_MODE_INFO[] modes;
            Query(out paths, out modes);
            foreach (var p in paths) {
                if (p.targetInfo.adapterId.LowPart == adapterLow && p.targetInfo.adapterId.HighPart == adapterHigh && p.targetInfo.id == targetId)
                    return p.targetInfo.targetAvailable;
            }
        } catch {}
        return false;
    }

    public static int ApplyDisplay(uint adapterLow, int adapterHigh, uint sourceId, uint targetId, uint width, uint height)
    {
        DISPLAYCONFIG_PATH_INFO[] paths;
        DISPLAYCONFIG_MODE_INFO[] modes;
        Query(out paths, out modes);
        DISPLAYCONFIG_PATH_INFO selected = new DISPLAYCONFIG_PATH_INFO();
        bool found = false;
        foreach (var p in paths) {
            if (p.targetInfo.adapterId.LowPart == adapterLow && p.targetInfo.adapterId.HighPart == adapterHigh && p.targetInfo.id == targetId) {
                selected = p; found = true; break;
            }
        }
        if (!found) return -1001;

        var topo = new DISPLAYCONFIG_PATH_INFO[1];
        topo[0] = selected;
        topo[0].flags = DISPLAYCONFIG_PATH_ACTIVE;
        topo[0].sourceInfo.modeInfoIdx = DISPLAYCONFIG_PATH_MODE_IDX_INVALID;
        topo[0].targetInfo.modeInfoIdx = DISPLAYCONFIG_PATH_MODE_IDX_INVALID;
        int rc = SetDisplayConfig(1, topo, 0, null, SDC_APPLY | SDC_TOPOLOGY_SUPPLIED | SDC_ALLOW_CHANGES);
        if (rc == 0) return 0;

        var mode = new DISPLAYCONFIG_MODE_INFO();
        mode.infoType = DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE;
        mode.id = sourceId;
        mode.adapterId.LowPart = adapterLow;
        mode.adapterId.HighPart = adapterHigh;
        mode.modeInfo.sourceMode.width = width == 0 ? 1920u : width;
        mode.modeInfo.sourceMode.height = height == 0 ? 1080u : height;
        mode.modeInfo.sourceMode.pixelFormat = DISPLAYCONFIG_PIXELFORMAT_32BPP;
        mode.modeInfo.sourceMode.position.x = 0;
        mode.modeInfo.sourceMode.position.y = 0;

        topo[0].sourceInfo.id = sourceId;
        topo[0].sourceInfo.adapterId.LowPart = adapterLow;
        topo[0].sourceInfo.adapterId.HighPart = adapterHigh;
        topo[0].sourceInfo.modeInfoIdx = 0;
        topo[0].targetInfo.modeInfoIdx = DISPLAYCONFIG_PATH_MODE_IDX_INVALID;
        rc = SetDisplayConfig(1, topo, 1, new DISPLAYCONFIG_MODE_INFO[] { mode }, SDC_APPLY | SDC_USE_SUPPLIED_DISPLAY_CONFIG | SDC_ALLOW_CHANGES | SDC_SAVE_TO_DATABASE);
        return rc;
    }

    // Returns the GDI device name (e.g. "\\.\DISPLAY2") for the active path to the given target.
    // Called after ApplyDisplay succeeds so the display is guaranteed active.
    public static string GetActiveSourceName(uint adapterLow, int adapterHigh, uint targetId)
    {
        try {
            DISPLAYCONFIG_PATH_INFO[] paths;
            DISPLAYCONFIG_MODE_INFO[] modes;
            Query(out paths, out modes);
            foreach (var p in paths) {
                if (p.targetInfo.adapterId.LowPart == adapterLow &&
                    p.targetInfo.adapterId.HighPart == adapterHigh &&
                    p.targetInfo.id == targetId &&
                    (p.flags & DISPLAYCONFIG_PATH_ACTIVE) != 0)
                {
                    var src = new DISPLAYCONFIG_SOURCE_DEVICE_NAME();
                    src.header.size = (uint)Marshal.SizeOf(typeof(DISPLAYCONFIG_SOURCE_DEVICE_NAME));
                    src.header.adapterId = p.sourceInfo.adapterId;
                    src.header.id = p.sourceInfo.id;
                    src.header.type = DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME;
                    if (DisplayConfigGetDeviceInfoSource(ref src) == 0)
                        return src.viewGdiDeviceName;
                }
            }
        } catch {}
        return null;
    }

    // Applies refresh rate (and optionally resolution) to a GDI device via ChangeDisplaySettingsEx.
    // Pass width=0 / height=0 to keep the current resolution and only change Hz.
    // Returns 0 on success (DISP_CHANGE_SUCCESSFUL).
    public static int SetRefreshRate(string gdiDeviceName, uint width, uint height, uint hz)
    {
        if (string.IsNullOrEmpty(gdiDeviceName) || hz == 0) return -1;
        var dm = new DEVMODE();
        dm.dmSize = (short)Marshal.SizeOf(typeof(DEVMODE));
        if (!EnumDisplaySettings(gdiDeviceName, ENUM_CURRENT_SETTINGS, ref dm)) return -2;
        dm.dmDisplayFrequency = (int)hz;
        dm.dmFields = DM_DISPLAYFREQUENCY;
        if (width > 0 && height > 0) {
            dm.dmPelsWidth  = (int)width;
            dm.dmPelsHeight = (int)height;
            dm.dmFields |= DM_PELSWIDTH | DM_PELSHEIGHT;
        }
        return ChangeDisplaySettingsEx(gdiDeviceName, ref dm, IntPtr.Zero, CDS_UPDATEREGISTRY, IntPtr.Zero);
    }
}
"@ -ErrorAction SilentlyContinue
# ============================================================
# Helpers
# ============================================================

$script:HasGetPnpDevice = [bool](Get-Command Get-PnpDevice -ErrorAction SilentlyContinue)
$script:ContainerScanIntervalMs = 5000
$script:CimFallbackIntervalMs = 30000
$script:LastContainerScanUtc = [datetime]::MinValue
$script:LastCimFallbackUtc = [datetime]::MinValue
$script:LastContainerPresentIds = @()
$script:LastCimPresentIds = @()

function Add-PresentControllerId {
    param(
        [System.Collections.Generic.HashSet[string]]$Set,
        [string]$Id
    )
    if (-not [string]::IsNullOrWhiteSpace($Id)) {
        [void]$Set.Add($Id.Trim())
    }
}

function Get-PresentControllerIds {
    try {
        $present = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

        if ($script:HasGetPnpDevice) {
            foreach ($id in $global:WatchedControllerIds) {
                try {
                    $dev = Get-PnpDevice -PresentOnly -InstanceId $id -ErrorAction SilentlyContinue
                    if ($dev) { Add-PresentControllerId $present $id }
                } catch {}
            }

            if ($global:WatchedContainerIds.Count -gt 0) {
                $now = [datetime]::UtcNow
                if (($now - $script:LastContainerScanUtc).TotalMilliseconds -ge $script:ContainerScanIntervalMs) {
                    $script:LastContainerScanUtc = $now
                    $containerPresent = [System.Collections.Generic.List[string]]::new()

                    # Container IDs are only needed for Xbox wireless adapter slot changes.
                    # Limit the scan to HID devices so the steady-state poll does not walk
                    # every PnP device on the machine.
                    $hidDevices = @(Get-PnpDevice -PresentOnly -Class HIDClass -ErrorAction SilentlyContinue)
                    if (-not $hidDevices -or $hidDevices.Count -eq 0) {
                        $hidDevices = @(Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
                            Where-Object { $_.InstanceId -match '(?i)^HID\\VID_045E' })
                    }

                    foreach ($dev in $hidDevices) {
                        $hid = [string]$dev.InstanceId
                        if ($hid -notmatch '(?i)^HID\\VID_045E.*PID_02EA') { continue }
                        try {
                            $prop = Get-PnpDeviceProperty -InstanceId $hid -KeyName 'DEVPKEY_Device_ContainerId' -ErrorAction SilentlyContinue
                            if ($prop -and $prop.Data) {
                                $cid = ([string]$prop.Data).Trim()
                                if ($global:WatchedContainerIds.Contains($cid)) {
                                    $containerPresent.Add($cid)
                                }
                            }
                        } catch {}
                    }

                    $script:LastContainerPresentIds = @($containerPresent | Sort-Object -Unique)
                }

                foreach ($cid in $script:LastContainerPresentIds) {
                    Add-PresentControllerId $present $cid
                }
            }
        }

        if ($present.Count -eq 0) {
            $now = [datetime]::UtcNow
            if ((-not $script:HasGetPnpDevice) -or (($now - $script:LastCimFallbackUtc).TotalMilliseconds -ge $script:CimFallbackIntervalMs)) {
                $script:LastCimFallbackUtc = $now
                $fallbackPresent = [System.Collections.Generic.List[string]]::new()
                $fallback = @(Get-CimInstance Win32_PnPEntity -ErrorAction SilentlyContinue)
                foreach ($dev in $fallback) {
                    $id = [string]$dev.DeviceID
                    if (-not [string]::IsNullOrWhiteSpace($id) -and $global:WatchedControllerIds.Contains($id)) {
                        $fallbackPresent.Add($id)
                    }
                }
                $script:LastCimPresentIds = @($fallbackPresent | Sort-Object -Unique)
            }

            foreach ($id in $script:LastCimPresentIds) {
                Add-PresentControllerId $present $id
            }
        }

        @($present | Sort-Object)
    } catch {
        Write-Log "Poll error: $($_.Exception.Message)"
        @()
    }
}

try {
    $initialPresent = @(Get-PresentControllerIds)
    Write-Log "Initial present watched controllers: $($initialPresent.Count)"
    foreach ($id in $initialPresent) { Write-Log "  present: $id" }

    # Log any Xbox controllers that are present but matched by neither instance path nor
    # container ID.  If a mapped controller never shows as connected, the wizard may need
    # to be re-run so it can capture both the current instance path AND the container ID.
    $xboxUnknown = @()
    if ($script:HasGetPnpDevice) {
        $xboxUnknown = @(Get-PnpDevice -PresentOnly -Class HIDClass -ErrorAction SilentlyContinue |
            Where-Object { $_.InstanceId -match 'VID_045E.*PID_02E[0-9A-F]|VID_045E.*IG_' -and
                           -not $global:WatchedControllerIds.Contains($_.InstanceId) })
    }
    foreach ($dev in $xboxUnknown) {
        # Suppress the NOTE if this device is already matched by container ID
        $matchedByContainer = $false
        if ($global:WatchedContainerIds.Count -gt 0) {
            try {
                $prop = Get-PnpDeviceProperty -InstanceId $dev.InstanceId -KeyName 'DEVPKEY_Device_ContainerId' -ErrorAction SilentlyContinue
                if ($prop -and $prop.Data -and $global:WatchedContainerIds.Contains(([string]$prop.Data).Trim())) {
                    $matchedByContainer = $true
                }
            } catch {}
        }
        if (-not $matchedByContainer) {
            Write-Log "  NOTE: Xbox controller present but not in watch list: $($dev.InstanceId)"
            Write-Log "        Re-run the setup wizard to update controller mappings"
                        }
    }
} catch {
    Write-Log "Initial present scan failed: $($_.Exception.Message)"
}

function Get-ProfileValue {
    param(
        [Parameter(Mandatory=$true)]$Profile,
        [Parameter(Mandatory=$true)][string]$Name,
        $Default = $null
    )

    if ($Profile -is [hashtable]) {
        if ($Profile.ContainsKey($Name)) { return $Profile[$Name] }
        return $Default
    }
    if ($Profile.PSObject.Properties[$Name]) { return $Profile.$Name }
    return $Default
}

function Resolve-CcdProfileTarget {
    param(
        [Parameter(Mandatory=$true)]$Profile,
        [string]$ProfileName = ""
    )

    $saved = [pscustomobject]@{
        AdapterLow      = [uint32](Get-ProfileValue $Profile 'AdapterLow' 0)
        AdapterHigh     = [int](Get-ProfileValue $Profile 'AdapterHigh' 0)
        SourceId        = [uint32](Get-ProfileValue $Profile 'SourceId' 0)
        TargetId        = [uint32](Get-ProfileValue $Profile 'TargetId' 0)
        DevicePath      = [string](Get-ProfileValue $Profile 'DevicePath' '')
        Friendly        = [string](Get-ProfileValue $Profile 'Friendly' '')
        IsResolved      = $false
        IsRemapped      = $false
        TargetAvailable = $false
        IsActive        = $false
        BlockReason     = ''
    }

    try {
        $resolved = [SofaCcd]::ResolveTarget(
            [uint32]$saved.AdapterLow,
            [int]$saved.AdapterHigh,
            [uint32]$saved.SourceId,
            [uint32]$saved.TargetId,
            [string]$saved.DevicePath,
            [string]$saved.Friendly
        )
        if ($resolved) {
            $isRemapped = (
                [uint32]$resolved.AdapterLow -ne [uint32]$saved.AdapterLow -or
                [int]$resolved.AdapterHigh -ne [int]$saved.AdapterHigh -or
                [uint32]$resolved.SourceId -ne [uint32]$saved.SourceId -or
                [uint32]$resolved.TargetId -ne [uint32]$saved.TargetId
            )
            return [pscustomobject]@{
                AdapterLow      = [uint32]$resolved.AdapterLow
                AdapterHigh     = [int]$resolved.AdapterHigh
                SourceId        = [uint32]$resolved.SourceId
                TargetId        = [uint32]$resolved.TargetId
                DevicePath      = [string]$resolved.DevicePath
                Friendly        = [string]$resolved.Friendly
                IsResolved      = $true
                IsRemapped      = $isRemapped
                TargetAvailable = [bool]$resolved.TargetAvailable
                IsActive        = [bool]$resolved.IsActive
                BlockReason     = ''
            }
        }
    } catch {
        Write-Log "WARNING: Could not re-resolve CCD target for '$ProfileName': $($_.Exception.Message)"
    }

    if (-not [string]::IsNullOrWhiteSpace([string]$saved.DevicePath)) {
        $saved.BlockReason = "Saved display '$($saved.Friendly)' is not currently present; refusing to apply this profile to a different HDMI target."
    }
    return $saved
}

function Invoke-DisplayProfile {
    param([string]$ProfileName)
    $p = $cfg_Profiles[$ProfileName]
    if (-not $p) { Write-Log "Unknown profile: $ProfileName"; return }

    $target = Resolve-CcdProfileTarget -Profile $p -ProfileName $ProfileName
    if ($target.PSObject.Properties['BlockReason'] -and $target.BlockReason) {
        Write-Log "WARNING: Profile '$ProfileName' skipped - $($target.BlockReason)"
        return
    }
    if (-not ($target.TargetId -and [uint32]$target.TargetId -gt 0)) {
        Write-Log "ERROR: Profile '$ProfileName' has TargetId=0 - re-run the setup wizard and click Save Profile on Step 3"
        return
    }

    Write-Log "Applying profile '$ProfileName'  FRL=$($p.FRL)  Audio=$($p.Audio)"

    $w = 0; $h = 0
    if ([string]$p.Resolution -match '^(\d+)x(\d+)$') { $w = [uint32]$Matches[1]; $h = [uint32]$Matches[2] }

    # Retry up to 4 times with 2 s between attempts. The display (especially an
    # HDMI TV) may not have finished link training when the controller first connects,
    # causing SetDisplayConfig to return ERROR_INVALID_PARAMETER (87). A short wait
    # is usually enough for targetAvailable to flip true.
    $rc = -1
    $lastTargetKey = ""
    for ($attempt = 1; $attempt -le 4; $attempt++) {
        $target = Resolve-CcdProfileTarget -Profile $p -ProfileName $ProfileName
        $targetKey = "$($target.AdapterHigh):$($target.AdapterLow):$($target.SourceId):$($target.TargetId)"
        if ($targetKey -ne $lastTargetKey) {
            if ($target.IsRemapped) {
                Write-Log "  Re-resolved CCD target for '$ProfileName' to targetId=$($target.TargetId) via saved display identity"
            }
            $lastTargetKey = $targetKey
        }
        if ($attempt -gt 1) {
            $avail = [SofaCcd]::GetTargetAvailable([uint32]$target.AdapterLow, [int]$target.AdapterHigh, [uint32]$target.TargetId)
            Write-Log "  CCD code $rc on attempt $($attempt-1) (targetAvailable=$avail) - waiting 2 s..."
            Start-Sleep -Seconds 2
        }
        $rc = [SofaCcd]::ApplyDisplay([uint32]$target.AdapterLow, [int]$target.AdapterHigh, [uint32]$target.SourceId, [uint32]$target.TargetId, $w, $h)
        if ($rc -eq 0) { break }
    }

    if ($rc -eq 0) {
        Write-Log "CCD apply succeeded for targetId=$($target.TargetId)"

        # Apply the configured refresh rate via ChangeDisplaySettingsEx.
        # CCD activates the display but lets Windows pick any Hz; this call enforces
        # the specific rate saved in the profile (e.g. 120 Hz for TV, 165 Hz for desk).
        $hz = [uint32]0
        $rhz = if ($p.ContainsKey('RefreshHz')) { [string]$p['RefreshHz'] } else { '' }
        if ($rhz -match '^\d+$') { $hz = [uint32]$rhz }
        if ($hz -gt 0) {
            Start-Sleep -Milliseconds 800   # let display link stabilise after topology switch
            $devName = [SofaCcd]::GetActiveSourceName([uint32]$target.AdapterLow, [int]$target.AdapterHigh, [uint32]$target.TargetId)
            if ($devName) {
                $rrc = [SofaCcd]::SetRefreshRate($devName, $w, $h, $hz)
                if ($rrc -eq 0) { Write-Log "Refresh rate set to $hz Hz on $devName" }
                else { Write-Log "WARNING: SetRefreshRate returned $rrc for $devName @ $hz Hz (display may not support this mode)" }
            } else {
                Write-Log "WARNING: Could not find active GDI source for targetId=$($target.TargetId) - refresh rate not applied"
            }
        }
    } else {
        $avail = [SofaCcd]::GetTargetAvailable([uint32]$target.AdapterLow, [int]$target.AdapterHigh, [uint32]$target.TargetId)
        Write-Log "ERROR: CCD apply failed with code $rc for profile '$ProfileName' (targetAvailable=$avail)"
    }

    # 2. Set frame rate limit (skip cleanly if disabled, or if cap is 0/Unlimited).
    # FRL Toggle may require elevation on some machines. SofaShift runs the watcher
    # unelevated by default; failures are logged without elevating user-writable scripts.
    $frlCap = 0
    $frlRaw = [string]$p.FRL
    Write-Log "FRL: profile FRL='$frlRaw' (raw value from config)"
    if ([int]::TryParse($frlRaw, [ref]$frlCap) -and $frlCap -gt 0) {
        if ($cfg_FRLToggle -and (Test-Path $cfg_FRLToggle)) {
            Write-Log "FRL: invoking '$cfg_FRLToggle' $frlCap"
            try {
                $proc = Start-Process -FilePath $cfg_FRLToggle `
                              -ArgumentList "$frlCap" `
                              -Wait -WindowStyle Hidden -PassThru -ErrorAction Stop
                Write-Log "FRL: frltoggle exit code = $($proc.ExitCode) (0 = success)"
                if ($proc.ExitCode -ne 0) {
                    Write-Log "FRL: NOTE - frltoggle returned non-zero. It may require administrator rights on this PC; display/audio/app switching will continue."
                }
            } catch {
                Write-Log "FRL ERROR: $($_.Exception.Message)"
            }
        } elseif ($cfg_FRLToggle) {
            Write-Log "WARNING: frltoggle configured but not found on disk: $cfg_FRLToggle"
        } else {
            Write-Log "FRL: frltoggle is not configured (cfg_FRLToggle is blank) - skipping FPS cap"
        }
    } else {
        Write-Log "FRL cap is 0/Unlimited - leaving frame rate uncapped"
    }

    # 3. Set audio device (delay lets HDMI audio appear after display switch)
    Start-Sleep -Milliseconds $cfg_AudioDelayMs
    if ([string]::IsNullOrWhiteSpace([string]$p.Audio)) {
        Write-Log "No audio device configured for this profile - skipping audio switch"
    } elseif (Test-Path $cfg_NirCmd) {
        & $cfg_NirCmd setdefaultsounddevice "$($p.Audio)" | Out-Null
        Write-Log "Audio set to: $($p.Audio)"
    } else {
        Write-Log "WARNING: nircmd not found: $cfg_NirCmd"
    }
}

function Start-HueSync {
    if (-not $cfg_HueSync -or -not (Test-Path $cfg_HueSync)) { return }
    $running = Get-Process -Name "HueSync" -ErrorAction SilentlyContinue
    if ($running) {
        Write-Log "Hue Sync already running (PID $($running[0].Id))"
        return
    }
    Write-Log "Starting Hue Sync"
    Register-LaunchedProcess -Label "Hue Sync" -Path $cfg_HueSync -ProcessNames @("HueSync","handler")
    Start-Process -FilePath $cfg_HueSync -WindowStyle Minimized
}

function Stop-HueSync {
    Stop-LaunchedProcesses -Label "Hue Sync"
}

function Register-LaunchedProcess {
    param(
        [Parameter(Mandatory=$true)][string]$Label,
        [string]$Path = "",
        [string[]]$ProcessNames = @()
    )

    if (-not $global:LaunchedProcesses) { $global:LaunchedProcesses = @{} }
    $names = @($ProcessNames | Where-Object { $_ })
    if ($names.Count -eq 0 -and $Path) { $names = @([System.IO.Path]::GetFileNameWithoutExtension($Path)) }
    $global:LaunchedProcesses[$Label] = [pscustomobject]@{
        Path = [string]$Path
        ProcessNames = $names
        LaunchedAt = Get-Date
    }
    Write-Log "Tracking launched $Label from $Path"
}

function Stop-LaunchedProcesses {
    param([Parameter(Mandatory=$true)][string]$Label)

    if (-not $global:LaunchedProcesses -or -not $global:LaunchedProcesses.ContainsKey($Label)) { return }
    $entry = $global:LaunchedProcesses[$Label]
    $names = @($entry.ProcessNames | Where-Object { $_ })
    foreach ($name in $names) {
        $procs = Get-Process -Name $name -ErrorAction SilentlyContinue
        foreach ($proc in @($procs)) {
            try {
                if ($proc.StartTime -lt $entry.LaunchedAt.AddSeconds(-2)) {
                    Write-Log "Skipping $Label PID $($proc.Id); it was already running before SofaShift launched it"
                    continue
                }
                if ($entry.Path -and $proc.Path -and ([string]$proc.Path -ne [string]$entry.Path) -and $name -ne "handler") {
                    Write-Log "Skipping $Label PID $($proc.Id); executable path does not match configured target"
                    continue
                }
                if ($entry.Path -and -not $proc.Path -and $name -ne "handler") {
                    Write-Log "Skipping $Label PID $($proc.Id); executable path could not be verified"
                    continue
                }
                Write-Log "Stopping launched $Label PID $($proc.Id)"
                $proc | Stop-Process -Force -ErrorAction SilentlyContinue
            } catch {
                Write-Log "Could not inspect or stop $Label PID $($proc.Id): $($_.Exception.Message)"
            }
        }
    }
    $global:LaunchedProcesses.Remove($Label)
}

function Start-CustomApp {
    param([object[]]$EnabledApps = $null)

    $apps = @()
    if (Get-Variable 'cfg_CustomApps' -Scope Global -ErrorAction SilentlyContinue) {
        $appIndex = 0
        foreach ($app in @($cfg_CustomApps)) {
            if (-not $app) { continue }
            $path = if ($app -is [hashtable] -and $app.ContainsKey('Path')) { [string]$app.Path } elseif ($app.PSObject.Properties['Path']) { [string]$app.Path } else { '' }
            $label = if ($app -is [hashtable] -and $app.ContainsKey('Label')) { [string]$app.Label } elseif ($app.PSObject.Properties['Label']) { [string]$app.Label } else { '' }
            if ($path) {
                $enabled = if ($EnabledApps -and $appIndex -lt $EnabledApps.Count) { [bool]$EnabledApps[$appIndex] } else { $true }
                $apps += [pscustomobject]@{ Label = $label; Path = $path; Enabled = $enabled }
                $appIndex++
            }
        }
    }
    if ($apps.Count -eq 0 -and (Get-Variable 'cfg_CustomApp' -Scope Global -ErrorAction SilentlyContinue) -and $cfg_CustomApp) {
        $label = if ((Get-Variable 'cfg_CustomAppLabel' -Scope Global -ErrorAction SilentlyContinue) -and $cfg_CustomAppLabel) { [string]$cfg_CustomAppLabel } else { 'Custom App' }
        $enabled = if ($EnabledApps -and $EnabledApps.Count -gt 0) { [bool]$EnabledApps[0] } else { $true }
        $apps += [pscustomobject]@{ Label = $label; Path = [string]$cfg_CustomApp; Enabled = $enabled }
    }
    foreach ($app in $apps) {
        if (-not $app.Enabled) {
            Write-Log "Custom app '$($app.Label)' skipped for active profile"
            continue
        }
        if (-not $app.Path -or -not (Test-Path $app.Path)) { continue }
        $procName = [System.IO.Path]::GetFileNameWithoutExtension($app.Path)
        $running = Get-Process -Name $procName -ErrorAction SilentlyContinue
        if ($running) {
            Write-Log "Custom app '$procName' already running (PID $($running[0].Id))"
            continue
        }
        Write-Log "Starting custom app '$($app.Label)': $($app.Path)"
        Register-LaunchedProcess -Label "Custom app" -Path $app.Path
        Start-Process -FilePath $app.Path
    }
}

function Stop-CustomApp {
    Stop-LaunchedProcesses -Label "Custom app"
}

function Stop-Playnite {
    Stop-LaunchedProcesses -Label "Playnite"
}

function Invoke-MinimizeAll {
    try { (New-Object -ComObject Shell.Application).MinimizeAll() } catch {}
}

function Invoke-DismissOSK {
    try { (New-Object -ComObject WScript.Shell).SendKeys('{ESC}') } catch {}
    Get-Process TabTip, osk -ErrorAction SilentlyContinue |
        Stop-Process -Force -ErrorAction SilentlyContinue
}

function Focus-Window {
    param([string]$TitleRegex, [int]$TimeoutMs = 6000)
    $sw = [Diagnostics.Stopwatch]::StartNew()
    while ($sw.ElapsedMilliseconds -lt $TimeoutMs) {
        $hwnd = [XCS.User32]::FindWindowByTitleRegex($TitleRegex)
        if ($hwnd -ne [IntPtr]::Zero) {
            Start-Sleep -Milliseconds 150
            [XCS.User32]::SetForegroundWindow($hwnd) | Out-Null
            return $true
        }
        Start-Sleep -Milliseconds 300
    }
    return $false
}

function Resolve-FocusTarget {
    param([string]$Target)
    $value = ([string]$Target).Trim()
    if ([string]::IsNullOrWhiteSpace($value)) { return 'Playnite' }
    if ($value -match '^(?i:windows desktop|desktop)$') { return 'Windows Desktop' }
    if ($value -match '^(?i:playnite)$') { return 'Playnite' }
    Write-Log "Unknown focus target '$value'; defaulting to Playnite"
    return 'Playnite'
}

function Invoke-ConfiguredFocus {
    param([string]$Target)
    $focusTarget = Resolve-FocusTarget $Target
    Invoke-MinimizeAll
    Invoke-DismissOSK
    if ($focusTarget -eq 'Windows Desktop') {
        Write-Log "Focus target is Windows Desktop - leaving desktop visible"
        return
    }
    if (-not (Focus-Window -TitleRegex 'Playnite')) {
        Start-Sleep -Milliseconds 400
        Invoke-DismissOSK
        [void](Focus-Window -TitleRegex 'Playnite')
    }
}

# ============================================================
# State
# ============================================================
$global:LastPresentIds   = @()
$global:LastAnyPresent   = $false
$global:ActiveProfile    = $null       # currently loaded profile name
$global:OfflineStartTime = $null       # when all controllers went offline
$global:LaunchedProcesses = @{}

# ============================================================
# Connect / Disconnect handlers
# ============================================================

function Handle-Connect {
    param([string]$DeviceId)

    # Look up profile by instance path first, then container ID fallback.
    $targetProfile = $global:CanonicalIdToProfile[$DeviceId]
    Write-Log "Connected: $DeviceId  =>  $targetProfile"

    # Reconnected within debounce window.
    # Only cancel cleanup silently if the reconnecting controller maps to the CURRENTLY-ACTIVE
    # profile. If it maps to a DIFFERENT profile (user grabbed a second controller), we still
    # need to switch, so fall through to the normal handling below.
    if ($global:OfflineStartTime -ne $null) {
        $elapsed = (Get-Date) - $global:OfflineStartTime
        if ($elapsed.TotalSeconds -lt $cfg_DebounceSeconds) {
            if ($targetProfile -and $targetProfile -eq $global:ActiveProfile) {
                Write-Log "Reconnect within debounce window - cancelling cleanup"
                $global:OfflineStartTime = $null
                return
            } else {
                Write-Log "Reconnect within debounce window - different profile '$targetProfile', applying switch"
                $global:OfflineStartTime = $null
                # fall through to normal switch
            }
        }
    }

    # First controller wins - once any profile is active, ignore additional controller
    # connections until all controllers disconnect and cleanup fires (setting ActiveProfile=null).
    if ($global:ActiveProfile -ne $null) {
        Write-Log "Profile '$global:ActiveProfile' already active - ignoring '$DeviceId' (first controller wins)"
        return
    }

    $global:ActiveProfile    = $targetProfile
    $global:OfflineStartTime = $null
    Invoke-DisplayProfile -ProfileName $targetProfile

    $activeProfileData = $cfg_Profiles[$targetProfile]
    $usePlaynite = if ($activeProfileData -and $activeProfileData.ContainsKey('UsePlaynite')) { [bool]$activeProfileData['UsePlaynite'] } else { $true }
    $useHueSync  = if ($activeProfileData -and $activeProfileData.ContainsKey('UseHueSync'))  { [bool]$activeProfileData['UseHueSync']  } else { $true }

    if ($usePlaynite) {
        if ($cfg_Playnite -and (Test-Path $cfg_Playnite)) {
            Write-Log "Launching Playnite"
            Register-LaunchedProcess -Label "Playnite" -Path $cfg_Playnite -ProcessNames @("Playnite.FullscreenApp","Playnite.DesktopApp")
            Start-Process -FilePath $cfg_Playnite
        } elseif ($cfg_Playnite) {
            Write-Log "WARNING: Playnite not found: $cfg_Playnite"
        }
    } else {
        Write-Log "Playnite skipped for profile '$targetProfile'"
    }

    if ($useHueSync) { Start-HueSync } else { Write-Log "Hue Sync skipped for profile '$targetProfile'" }

    $useCustomApps = $null
    if ($activeProfileData -and $activeProfileData.ContainsKey('UseCustomApps')) { $useCustomApps = @($activeProfileData['UseCustomApps']) }
    $useCustomApp = if ($activeProfileData -and $activeProfileData.ContainsKey('UseCustomApp')) { [bool]$activeProfileData['UseCustomApp'] } else { $true }
    if ($useCustomApps -and $useCustomApps.Count -gt 0) {
        if ($useCustomApps -contains $true) { Start-CustomApp $useCustomApps } else { Write-Log "Custom apps skipped for profile '$targetProfile'" }
    } elseif ($useCustomApp) {
        Start-CustomApp
    } else {
        Write-Log "Custom app skipped for profile '$targetProfile'"
    }

    Start-Sleep -Milliseconds 400
    Invoke-MinimizeAll
    Invoke-DismissOSK
    if (-not (Focus-Window -TitleRegex $cfg_FocusTarget)) {
        Start-Sleep -Milliseconds 400
        Invoke-DismissOSK
        [void](Focus-Window -TitleRegex $cfg_FocusTarget)
    }
}

function Handle-Disconnect {
    param([string]$DeviceId)
    Write-Log "Disconnected: $DeviceId"
    # OfflineStartTime is set in the main loop when $anyPresent flips to false
}

function Invoke-DisconnectCleanup {
    Write-Log "No controllers for $cfg_DebounceSeconds s - running cleanup"

    Stop-Playnite
    Stop-HueSync
    Stop-CustomApp
    Invoke-DisplayProfile -ProfileName $cfg_DesktopProfile

    $global:ActiveProfile    = $null
    $global:OfflineStartTime = $null
    Write-Log "Cleanup complete"
}

# ============================================================
# Main polling loop
# ============================================================
while ($true) {
    $presentIds = Get-PresentControllerIds
    $anyPresent = ($presentIds.Count -gt 0)

    # Edge: newly connected
    foreach ($id in $presentIds) {
        if ($global:LastPresentIds -notcontains $id) {
            Handle-Connect -DeviceId $id
        }
    }

    # Edge: newly disconnected
    foreach ($id in $global:LastPresentIds) {
        if ($presentIds -notcontains $id) {
            Handle-Disconnect -DeviceId $id
        }
    }

    # Track when all controllers went offline (debounce start)
    if ($anyPresent) {
        $global:OfflineStartTime = $null
    } elseif ($global:LastAnyPresent -and -not $anyPresent) {
        $global:OfflineStartTime = Get-Date
        Write-Log "All controllers offline - starting $cfg_DebounceSeconds s debounce"
    }

    # Fire cleanup once debounce period expires
    if (-not $anyPresent -and $global:OfflineStartTime -ne $null) {
        $elapsed = (Get-Date) - $global:OfflineStartTime
        if ($elapsed.TotalSeconds -ge $cfg_DebounceSeconds) {
            Invoke-DisconnectCleanup
        }
    }

    $global:LastPresentIds = $presentIds
    $global:LastAnyPresent = $anyPresent

    Start-Sleep -Milliseconds $script:PollMs
}












